# sync by notion-stite
baseURL = "https://ns-doc.env.wtf/"
title = "Notion-Site Docs"
enableRobotsTXT = true
# this example loads the theme as hugo module
# comment out line below, and uncomment the line after it if you prefer to load the theme normally
theme =["compose","notion-site-theme"]  # edit this if you'ld rather use a fork of this repo
# theme = "compose"
enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "RSS","JSON"]

RelativeURLs=true
CanonifyURLs=true