# sync by notion-stite
#  menu items
[[main]]
  name = "Blog Example"
  weight = 5
  url = "https://blog.env.wtf/"

[[main]]
  name = "Docs"
  weight = 2
  url = "docs/"


[[main]]
  name = "Example"
  weight = 3
  url = "https://www.notion.so/2bd00e5dfff3449ba81e0142f8af9bbb"