name: build
on:
  schedule:  
    - cron: "0 */12 * * *"  
  workflow_dispatch:  
jobs:
  sync:
    name: Sync from notion
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - name: Ensure write permissions
        run: |
          if [ -d "./content" ]; then
            chmod -R u+w ./content
          else
            echo "Directory ./content does not exist. Skipping chmod."
          fi
      - name: Force sync with origin/main
        run: |
          git fetch origin
          git reset --hard origin/main
          git clean -fd          
      - name: Clean the old post
        run: |
          rm -rf ./content/*
          ls ./content || echo "Content directory is clean"
      - name: notion-site
        uses: nonacosa/notion-site@master
        env:
          NOTION_SECRET : ${{ secrets.NOTION_SECRET }}
      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
          
      - name: Set up Git
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Actions"
 
      - name: Commit new results
        run: |
          git add --all
          git commit -m "New results" || echo "No changes to commit"
      
      - name: Push changes
        id: push_changes
        run: |
          git push origin main || echo "Push failed or no changes to push"
          echo "push_success=true" >> $GITHUB_OUTPUT

      - name: Setup Hugo
        if: steps.push_changes.outputs.push_success == 'true'
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - uses: actions/cache@v2
        if: steps.push_changes.outputs.push_success == 'true'
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - name: Build
        if: steps.push_changes.outputs.push_success == 'true'
        run: hugo --minify

      - name: Deploy
        if: steps.push_changes.outputs.push_success == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
